sudo: required
dist: trusty
language: python
matrix:
  include:
   - env: TOXENV=py34-dj111
     python: 3.4
   - env: TOXENV=py35-dj111
     python: 3.5
   - env: TOXENV=py36-dj111
     python: 3.6
   - env: TOXENV=py34-dj20
     python: 3.4
   - env: TOXENV=py35-dj20
     python: 3.5
   - env: TOXENV=py36-dj20
     python: 3.6
   - env: TOXENV=py36-dj21
     python: 3.6
   - env: TOXENV=flake8
     python: 3.5
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - pip install tox
script:
  - docker-compose -f tests/testapp/docker-compose.yaml up -d firefox hub
  - tox
